# Generated by Django 4.1.6 on 2023-02-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20230211_0616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='modle',
            new_name='model',
        ),
    ]
